/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package onebrc.java;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        showString();
    }

    private static void showString() {
        String s = "";
        for (int i = 0; i < 100; i++) {
            s += "hello";
        }
    }
}
